package com.machinelearning.playcarddetect.modules.client
enum class DeviceStats{
    NOTDETECTED,
    DEVICE_OPENAPP_COMPLETED,
    DEVICE_OPENAPP_FAILED,
    DEVICE_STARTCAPTURE_COMPLETED,
    DEVICE_STARTCAPTURE_FAILED,
    DEVICE_OPENGAMEMENU_COMPLETED,
    DEVICE_OPENGAMEMENU_FAILED,
    DEVICE_OPENCHONBANSCREEN_COMPLETED,
    DEIVCE_OPENCHONBANSCREEN_FAILED,
    INGAMEMENU,
    INROOMLIST,
    GAMERUNNING,
    WAITINGCLIENT

}